### ISSUE TITLE
CreateList unsafe correction

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop-factory_bot#100]
Hey guys! I had a non-safe-autocorrection happen:

```diff
- 4.times { create(:product_review, created_at: Time.now.utc + rand(100).days) }
+ create_list(:product_review, 3, created_at: Time.now.utc + rand(100).days)
```

From my reading of the thread, this `rand(100)` should have been picked up as a method call, which should disqualify the offence for auto-correction. Is this a bug, or did I understand incorrectly?

Cheers.

_Originally posted by @amomchilov in https://github.com/rubocop/rubocop-rspec/issues/1087#issuecomment-1944908668_

**Comment by ydah** [comment]
I made the following changes in the latest master, but did not reproduce them. Could you tell me the version?

```
Δ spec/rubocop/cop/factory_bot/create_list_spec.rb
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

──────────────────────────────────────────────────────────────┐
• 194: RSpec.describe RuboCop::Cop::FactoryBot::CreateList do │
──────────────────────────────────────────────────────────────┘
 194⋮ 194│      RUBY
 195⋮ 195│    end
 196⋮ 196│
    ⋮ 197│    it 'ignores n.times.map when create call does have method calls ' \
    ⋮ 198│       'with `+` operator' do
    ⋮ 199│      expect_no_offenses(<<~RUBY)
    ⋮ 200│        4.times { create(:product_review, created_at: Time.now.utc + rand(100).days) }
    ⋮ 201│      RUBY
    ⋮ 202│    end
    ⋮ 203│
 197⋮ 204│    it 'flags usage of Array.new(n) with no arguments' do
 198⋮ 205│      expect_offense(<<~RUBY)
 199⋮ 206│        Array.new(3) { create(:user) }
```

**Comment by pirj** [comment]
Cc @amomchilov

**Comment by amomchilov** [comment]
Hey @pirj and @ydah, thanks for filing this and taking a stab at this!

I did some digging, and found that the presence of this `:some_trait` makes the difference between being detected, and not:

```ruby
4.times { create(:product_review, relevancy_score: Time.now.utc + rand(100).days) } # No offence
4.times { create(:product_review, :some_trait, relevancy_score: Time.now.utc + rand(100).days) } # Offence
```

Here are the version I'm using, and the demo run:

```sh
$ bundle exec rubocop -V
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.3.0) [arm64-darwin23]
  - rubocop-factory_bot 2.24.0
  ...

$ bundle exec rubocop --only=FactoryBot/CreateList the_file.rb

...

the_file.rb:123:5: C: [Correctable] FactoryBot/CreateList: Prefer create_list.
    4.times { create(:product_review, :some_trait, relevancy_score: Time.now.utc + rand(100).days) }
        ^^^^^^^
```

**Comment by ydah** [comment]
@amomchilov Thank you for telling me the version! That problem is solved in [v2.25.1](https://github.com/rubocop/rubocop-factory_bot/releases/tag/v2.25.1). So, can you give me a version of rubocop-factory_ bot?

* https://github.com/rubocop/rubocop-factory_bot/commit/85bae8d0c782ba1b467d63e928a86f767ade9472

**Comment by pirj** [comment]
Already fixed.

**Comment by amomchilov** [comment]
Confirmed! This false error went away with `rubocop-factory_bot 2.25.1`

Sorry for the noise here gents, I'll double check my version is up-to-date before posting in the future!
