### ISSUE TITLE
FactoryBot/AssociationStyle error on nested factories

### ISSUE THREAD

**Issue by jaydorsey** [rubocop/rubocop-factory_bot#113]
I ran the corrector w/ this cop on our codebase, using the `explicit` style. It made one correction which broke factorybot.

I wrote a test that reproduced the behavior below.

The problem is a nested factory that looks like `factory :active_article, traits: [:approved, :active]` and:

1. It gets identified as an error (should it be?)
2. It gets corrected to `association :factory, :active_article, traits: [:active, :approved]` which breaks the factory

The interesting thing is if I just add a `do;end` block to my `:active_article` factory, it ignores the error. I have a draft PR I'm going to push up shortly.

```
    context 'when implicit association has factory and traits' do
      it 'registers and corrects an offense' do
        expect_no_offenses(<<~RUBY)
          factory :article do
            traits :approved do
              approved { true }
            end

            traits :active do
              active { true }
            end

            factory :active_article, traits: [:approved, :active]
          end
        RUBY
      end
    end
```

**Comment by pirj** [comment]
Thanks for reporting. This looks like a bug, and needs to be fixed if so.
