### ISSUE TITLE
FactoryBot/CreateList problem

### ISSUE THREAD

**Issue by alec-c4** [rubocop/rubocop-factory_bot#129]
Hey,
rubocop-factory_bot version 2.26.0 causes problem, described here https://github.com/rubocop/rubocop-rspec/issues/1916 May I ask you to check it?

**Comment by joshbuker** [comment]
Can confirm, latest version `2.26.0` fails with:

```
Error: Property AutoCorrect of cop FactoryBot/CreateList is supposed to be a boolean and contextual is not.
```

Rolling back to `~> 2.25.0` as a temporary workaround appears to work.

**Comment by pirj** [comment]
The latest version is [2.26.1](https://rubygems.org/gems/rubocop-factory_bot/versions/2.26.1), and it's [fixed](https://github.com/rubocop/rubocop-factory_bot/blob/master/CHANGELOG.md#2261-2024-06-12) there.
Just the `bundle update --conservative rubocop-factory_bot` won't be sufficient, you have to update `rubocop`, too.

**Comment by joshbuker** [comment]
This fails with both RuboCop and rubocop factory bot open ended, but I'll double check when I get home to confirm exact versions.
