### ISSUE TITLE
Disable `ConsistentParenthesesStyle` by default: redundant with `Style/` config

### ISSUE THREAD

**Issue by thejonroberts** [rubocop/rubocop-factory_bot#132]
This is marked as a 'pending' rule, so I'm not 100% this will be enabled by default, but that seems to be the case more often than not with rubocop plugins.

Unless I'm missing some gotcha, FactoryBot method calls are... just method calls! I would prefer letting the base Rubocop configuration govern the styles for ALL method calls. The methods can be used in many different contexts, as illustrated by #84 and [#15](https://github.com/rubocop/rubocop-factory_bot/issues/15)  . I think the most reasonable default is to not enforce parens vs. no-parens.

Enforcing one style by default also increases the pain of installing the gem in an existing project. I recently added rubocop-factory_bot to a project, and this was the only rule that needed configuration. Otherwise I'm very happy with the experience, it was worth it!

I appreciate that some people want to treat these methods one way or the other consistently. I just think the rule should be opt-in.

**Comment by pirj** [comment]
Cops are pending until the next major release.

according to [this](https://rubystyle.guide/#no-dsl-decorating) Ruby style guide guideline, opposed style may apply, and this is why we have special case cop for FactoryBot DSL.

Thanks for sharing, and for the warm words! You’re always welcome.
