### ISSUE TITLE
No failure message for cop violation

### ISSUE THREAD

**Issue by brentgreeff** [rubocop/rubocop-factory_bot#133]
```yml
# @example EnforcedStyle: symbol (default)
      #   # bad
      #   create('user')
      #   build "user", username: "NAME"
```
I believe I am breaking this rule with `before { create('project') }`

I can see the cop being loaded, and the file where I break this rule is also checked.

```bash
bin/rubocop  --debug
configuration from /Users/brent/projects/assessments/confab/.rubocop.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-rspec-3.1.0/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-rspec-3.1.0/config/default.yml
Default configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-1.66.1/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-capybara-2.21.0/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-capybara-2.21.0/lib/../config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-factory_bot-2.26.1/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-factory_bot-2.26.1/lib/../config/default.yml
Inheriting configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-rails-omakase-1.0.0/rubocop.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-performance-1.22.1/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-performance-1.22.1/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-rails-2.26.2/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-rails-2.26.2/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-minitest-0.36.0/config/default.yml
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-minitest-0.36.0/config/default.yml
Use parallel by default.
Running parallel inspection
```

Can you recommend how I can debug this further?
I am using Rails 8.0.0.beta1.

**Comment by pirj** [comment]
Sorry, what cop?

**Comment by brentgreeff** [comment]
configuration from /Users/brent/.rvm/gems/ruby-3.3.5@confab/gems/rubocop-factory_bot-2.26.1/lib/../config/default.yml

this one.

`before { create('project') }`

is this correct according to this gem?

**Comment by pirj** [comment]
What of the cops you expected to fail? https://docs.rubocop.org/rubocop-factory_bot/cops.html

You’ve already provided an excerpt from the cop’s documentation. May I kindly ask you to also put the cop’s name in the issue title or description?

> Can you recommend how I can debug this further?

The above will be a solid first step.
After that, I suggest checking the cop’s spec. Does it look into hooks? Might be not. If not - send a PR with a failing spec. Kindly appreciated if you add specs for both styles.

Next, we can discuss in the PR how to actually fix the issue.

At a glance, I can’t tell why it doesn’t work.
Also, the “Explicit” option is confusing.

**Comment by ydah** [comment]
@brentgreeff  Thank you for your report. Please re-open this PR and let us know when you have more information. Until then, we will close the PR once.
