### ISSUE TITLE
`FactoryBot/FactoryNameStyle` thinks that Rails generate is a factory_bot method.

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop-factory_bot#3]
This is a Rails built in method: https://guides.rubyonrails.org/generators.html#generate

```
RSpec/FactoryBot/FactoryNameStyle: Use symbol to refer to a factory.
    generate 'blacklight:install', '--devise'
             ^^^^^^^^^^^^^^^^^^^^
```             

This is not a factory, and when it is autocorrected, the generator doesn't run correctly.

**Comment by pirj** [comment]
You should disable `FactoryBot/FactoryNameStyle` in generator specs using the following in `spec/generators/.rubocop.yml`:
```yml
FactoryBot/FactoryNameStyle:
  Enable: false
```

Or to exclude certain directories from the project `.rubocop.yml` file:
```yml
FactoryBot/FactoryNameStyle:
  Exclude:
    - "**/spec/generators/**/*.rb"
```
