### ISSUE TITLE
`FactoryBot/FactoryAssociationWithStrategy` should not check in `transient` block

### ISSUE THREAD

**Issue by tagliala** [rubocop/rubocop-factory_bot#39]
Sorry, I may did not understand correctly, but, as per https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#with-associations

> Transient [associations](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#associations) are not supported in factory_bot. Associations within the transient block will be treated as regular, non-transient associations.
>
> If needed, you can generally work around this by building a factory within a transient attribute:

So I expect

```rb
FactoryBot.define do
  factory :post do
    transient do
      user { create(:user) }
    end
  end
end
```

not to be considered an offense

**Comment by tagliala** [comment]
Hi,

apologies for the unclear scenario, but in the transient block there is not an association

As per https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#transient-attributes

> Transient attributes are attributes only available within the factory definition, and not set on the object being built. This allows for more complex logic inside factories.

`user` is not an attribute of the post, so `user=` is not defined and association will fail.

Here it is maybe a better example

```rb
FactoryBot.define do
  factory :post do
    transient do
      external_website { create(:external_website) }
    end

    title { "A post talking about #{external_website}" }
    link { external_website.url }
  end
end
```

Post does not belong to `external_website`, but the external website may be needed for complex logic inside the factory

Hope that this clarifies

**Comment by pirj** [comment]
Understood.

Do you really need to `create` the `external_website`? Would `attributes_for` work? Do you rely on `ExternalWebsite` model callbacks to populate certain attributes that you refer to from the `:post` factory?

Hardcoding a strategy, specifically `create` is known to be a source of major performance impacts on the growing spec suites, and is hard to refactor with multiple interdependent factories.

**Comment by pirj** [comment]
> FactoryBot's documentation works better

```ruby
# `user` has many posts, but it does not belong to a `post`.
# `post` will be used for complex logic in the factory
```

Please accept my apologies, is this note from the `factory_bot` documentation, or is it just your comment to it, @tagliala ?

If `user` has many `post`s and you want to have one:

> for a solution that works with build, build_stubbed, and create (although it doesn't work well with attributes_for), you can use inline associations:

```ruby
    factory :user_with_posts do
      posts { [association(:post)] }
    end
```

If a `user` does not belong to a `post`, can you please help me understand, how exactly is a single `post` "will be used for complex logic in the factory"?

**Comment by tagliala** [comment]
Sorry again for not providing enough information, I can clarify further

> Do you really need to create the external_website?

Some transient attributes we use are `ActiveModel` objects that are convenient to initialize through a factory

> Hardcoding a strategy, specifically create is known to be a source of major performance impacts

I'm making this change wherever I can, because this cop is helping identifying unwanted `create`s, but the `transient` block has a different purpose

> Please accept my apologies, is this note from the factory_bot documentation, or is it just your comment to it, @tagliala ?

Just my comment that can be added to FactoryBot documentation to clarify

> If a user does not belong to a post, can you please help me understand, how exactly is a single post "will be used for complex logic in the factory"?

I think the one in the documentation is just an example, and mine are examples too

If I should do an example from my domain logic, let's say that we have a plan with a fiscal year start date and End date. Fiscal year are not stored in the database, but they have some logic.

```
FactoryBot.define do
  factory :plan do
    transient do
      fiscal_year { create(:fiscal_year) }
    end

    fiscal_year_start { fiscal_year.start_date }
    fiscal_year_end { fiscal_year.end_date }
  end
end
```

This can of course be achieved by passing dates directly to the plan, but if we want to create a plan from another object's fiscal year, it is convenient to pass it as a transient object

```rb
# before
create(:plan, fiscal_year_start: activity.fiscal_year.start_date, fiscal_year_end: activity.fiscal_year.start_date)

# after
create(:plan, fiscal_year: activity.fiscal_year)
```

**Comment by pirj** [comment]
Ah, that makes total sense. Thank you!

**Comment by jhirn** [comment]
> Would adding a configuration option to the cop, like `IgnoreFactories` would work?

The work around above to use `association` works by accident but it's entirely accurate.

Adding an option to ignore transients would be awesome.  Debatable if this would be on by default since `association` never makes sense in a transient, it would just be a regular ol' attribute at that point.
