### ISSUE TITLE
`FactoryBot/CreateList` with 1 item conflicts with `Lint/UselessTimes`

### ISSUE THREAD

**Issue by michaelglass** [rubocop/rubocop-factory_bot#49]
`FactoryBot/CreateList`

```ruby
foos = [ create(:foo) ]
```

autocorrects to 

```ruby
foos = 1.times.map { create(:foo) }
```

which `Lint/UselessTimes` calls invalid

easy enough to resolve by using `create_list(:foo, 1)` or `foo = create(:foo); foos = [foo]` but just wanted to surface this funky auto-correct. Thank you maintainers!

**Comment by ydah** [comment]
@michaelglass Thank you for your report! I think this PR will solve this issue.
- https://github.com/rubocop/rubocop-factory_bot/pull/48
