### ISSUE TITLE
Improve `FactoryBot/CreateList` with `Performance/TimesMap` default code

### ISSUE THREAD

**Issue by mobilutz** [rubocop/rubocop-factory_bot#66]
The `FactoryBot/CreateList` creates `.times.map` syntax by default.

And then there is the Performance/TimesMap` cop, that changes `.times.map` to `Array(x)` syntax.

Why not make `FactoryBot/CreateList` use the `Array(x)` syntax by default?

PS: I did want to open a PullRequest, but I think this first should be talked over if it is even a good idea.

**Comment by pirj** [comment]
> creates .times.map syntax by default.

[Does it](https://github.com/rubocop/rubocop-factory_bot/blob/f4892e2cb419dd7a119b2311aa01d2a50328920a/config/default.yml#L59)?

It seems to [autocorrect to ‘create_list’](https://github.com/rubocop/rubocop-factory_bot/blob/f4892e2cb419dd7a119b2311aa01d2a50328920a/spec/rubocop/cop/factory_bot/create_list_spec.rb#L19).

Do you mean it does this when EnforcedStyle is :n_times?

I see that Performance/TimesMap doesn’t have a choice of styles. Anyway, we don’t know what cops are out there, and it’s fine to leave the code for other cops to inspect/ further correct. Notable example would be indentation and empty lines.

I’d rather not, even though ‘.times.map’ can be sub-optimal.

In addition to that, TimesMap is unsafe to autocorrect with non-positive argument. Frankly, I don’t know how would ‘create_list(:user, -1)’ work, but I’d stay away.
