### ISSUE TITLE
FactoryBot/IdSequence has wrong release version

### ISSUE THREAD

**Issue by jcoyne** [rubocop/rubocop-factory_bot#72]
https://github.com/rubocop/rubocop-factory_bot/blob/5589c191c29059dff9d6dc540f04428bda0901f5/config/default.yml#L106

Shouln't this be 2.24.0?

**Comment by pirj** [comment]
Thanks for noticing!

Some other cops’ ‘VersionUpdated’ is’<<next>>’, too. @ydah di you think the release script failed to substitute that dor a release version somehow?
