### ISSUE TITLE
How to extend `FactoryBot/CreateList` ?

### ISSUE THREAD

**Issue by leoarnold** [rubocop/rubocop-factory_bot#9]
FactoryBot actually has a few more `list` methods than just `create_list`:

```ruby
3.0.2 :006 > pp FactoryBot::Syntax::Methods.instance_methods.sort
[:attributes_for,
 :attributes_for_list,
 :attributes_for_pair,
 :build,
 :build_list,
 :build_pair,
 :build_stubbed,
 :build_stubbed_list,
 :build_stubbed_pair,
 :create,
 :create_list,
 :create_pair,
 :generate,
 :generate_list,
 :null,
 :null_list,
 :null_pair]
```

I would like to add these, but then the cop name `CreateList` does not fit any more. Maybe `MultipleInstances` would be more fitting.

Can I do that? How do I inform RuboCop about a renamed cop?

**Comment by pirj** [comment]
It's unclear what is the course of action with this.
